# Generated by Django 3.1.2 on 2022-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleCode', models.CharField(max_length=20, verbose_name='moduleCode')),
                ('moduleName', models.CharField(max_length=20, verbose_name='moduleName')),
                ('date', models.CharField(max_length=20, verbose_name='date')),
                ('file', models.FileField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'File',
            },
        ),
    ]
