# Generated by Django 3.1.2 on 2022-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, verbose_name='userId')),
                ('name', models.TextField()),
                ('moduleCode', models.CharField(max_length=20, verbose_name='moduleCode')),
                ('moduleName', models.CharField(max_length=20, verbose_name='moduleName')),
                ('date', models.CharField(max_length=20, verbose_name='date')),
                ('attendence', models.BooleanField()),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
