# Generated by Django 3.1.2 on 2022-09-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendence',
            table='Attendence',
        ),
    ]
